name: Auto Update

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:

  auto_update:
    name: Auto Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Supported Versions
        id: auto-update-and-commit
        run: echo "::set-output name=ver_updated::$(make auto-update-and-commit)"

      - name: cancelling
        uses: andymckay/cancel-action@0.2
        if: ${{ steps.auto-update-and-commit.outputs.ver_updated == '0' }}

      - name: cancelling
        uses: andymckay/cancel-action@0.2
        if: ${{ job.status != 'success' }}

  docker_build:
    strategy:
      matrix:
        distro: [alpine, amazonlinux, centos, debian, fedora, ubuntu]

    name: Build Docker
    runs-on: ubuntu-latest
    needs: auto_update
    steps:
      - uses: actions/checkout@v2

      - name: Cleanup metadata artifacts
        run: rm -rf docs/metadata/*

      - name: Build images
        run: make build-${{ matrix.distro }}

      - name: Test images
        run: make test-${{ matrix.distro }}

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login  -u ${{ github.actor }} --password-stdin
        if: github.ref == 'refs/heads/master'

      - name: Push images
        run: make push-${{ matrix.distro }}
        if: github.ref == 'refs/heads/master'

      - name: Archive metadata artifacts
        uses: actions/upload-artifact@v2
        with:
          name: metadata-${{ matrix.distro }}
          path: docs/metadata
          retention-days: 1

  metadata:
    name: Generates Metadata
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - uses: actions/checkout@v2

      - name: Restore amazonlinux metadata artifacts
        uses: actions/download-artifact@v2
        with:
          name: metadata-amazonlinux
          path: docs/metadata

      - name: Restore centos metadata artifacts
        uses: actions/download-artifact@v2
        with:
          name: metadata-centos
          path: docs/metadata

      - name: Restore debian metadata artifacts
        uses: actions/download-artifact@v2
        with:
          name: metadata-debian
          path: docs/metadata

      - name: Restore fedora metadata artifacts
        uses: actions/download-artifact@v2
        with:
          name: metadata-fedora
          path: docs/metadata

      - name: Restore ubuntu metadata artifacts
        uses: actions/download-artifact@v2
        with:
          name: metadata-ubuntu
          path: docs/metadata

      - name: Push metadata
        run: make auto-commit-metadata
        if: github.ref == 'refs/heads/master'

  auto_tag:
    name: Create Release
    runs-on: ubuntu-latest
    needs: metadata
    steps:
      - uses: actions/checkout@v2

      - name: Create Release
        run: make release