name: Auto Update

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch: ~

jobs:

  auto_update:
    name: Auto Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Supported Versions
        id: auto-update-and-commit
        run: make auto-update-and-commit

      - name: Repository Dispatch
        if: ${{ success() }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          event-type: autoupdate

      - name: Create Release
        run: make release
