name: Docker Builds

on:
  push:
    branches:
      - master
  pull_request:
    type:
      - opened
      - synchronize

jobs:
  docker_alpine:
    name: Build Docker Alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cleanup metadata artifacts
        run: rm -rf docs/metadata/*

      - name: Build images
        run: make build-alpine

      - name: Test images
        run: make test-alpine

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login  -u ${{ github.actor }} --password-stdin
        if: github.ref == 'refs/heads/master'

      - name: Push images
        run: make push-alpine
        if: github.ref == 'refs/heads/master'

      - name: Archive metadata artifacts
        uses: actions/upload-artifact@v2
        with:
          name: metadata-alpine
          path: docs/metadata
          retention-days: 1

  docker_amazonlinux:
    name: Build Docker Amazon Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cleanup metadata artifacts
        run: rm -rf docs/metadata/*

      - name: Build images
        run: make build-amazonlinux

      - name: Test images
        run: make test-amazonlinux

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login  -u ${{ github.actor }} --password-stdin
        if: github.ref == 'refs/heads/master'

      - name: Push images
        run: make push-amazonlinux
        if: github.ref == 'refs/heads/master'

      - name: Archive metadata artifacts
        uses: actions/upload-artifact@v2
        with:
          name: metadata-amazonlinux
          path: docs/metadata
          retention-days: 1

  docker_centos:
    name: Build Docker CentOS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cleanup metadata artifacts
        run: rm -rf docs/metadata/*

      - name: Build images
        run: make build-centos

      - name: Test images
        run: make test-centos

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login  -u ${{ github.actor }} --password-stdin
        if: github.ref == 'refs/heads/master'

      - name: Push images
        run: make push-centos
        if: github.ref == 'refs/heads/master'

      - name: Archive metadata artifacts
        uses: actions/upload-artifact@v2
        with:
          name: metadata-centos
          path: docs/metadata
          retention-days: 1

  docker_debian:
    name: Build Docker Debian
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cleanup metadata artifacts
        run: rm -rf docs/metadata/*

      - name: Build images
        run: make build-debian

      - name: Test images
        run: make test-debian

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login  -u ${{ github.actor }} --password-stdin
        if: github.ref == 'refs/heads/master'

      - name: Push images
        run: make push-debian
        if: github.ref == 'refs/heads/master'

      - name: Archive metadata artifacts
        uses: actions/upload-artifact@v2
        with:
          name: metadata-debian
          path: docs/metadata
          retention-days: 1

  docker_fedora:
    name: Build Docker Fedora
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cleanup metadata artifacts
        run: rm -rf docs/metadata/*

      - name: Build images
        run: make build-fedora

      - name: Test images
        run: make test-fedora

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login  -u ${{ github.actor }} --password-stdin
        if: github.ref == 'refs/heads/master'

      - name: Push images
        run: make push-fedora
        if: github.ref == 'refs/heads/master'

      - name: Archive metadata artifacts
        uses: actions/upload-artifact@v2
        with:
          name: metadata-fedora
          path: docs/metadata
          retention-days: 1

  docker_ubuntu:
    name: Build Docker Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cleanup metadata artifacts
        run: rm -rf docs/metadata/*

      - name: Build images
        run: make build-ubuntu

      - name: Test images
        run: make test-ubuntu

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login  -u ${{ github.actor }} --password-stdin
        if: github.ref == 'refs/heads/master'

      - name: Push images
        run: make push-ubuntu
        if: github.ref == 'refs/heads/master'

      - name: Archive metadata artifacts
        uses: actions/upload-artifact@v2
        with:
          name: metadata-ubuntu
          path: docs/metadata
          retention-days: 1

  metadata:
    name: Generates Metadata
    runs-on: ubuntu-latest
    needs: [docker_alpine, docker_amazonlinux, docker_centos, docker_debian, docker_fedora, docker_ubuntu]
    steps:
      - uses: actions/checkout@v2

      - name: Restore amazonlinux metadata artifacts
        uses: actions/download-artifact@v2
        with:
          name: metadata-amazonlinux
          path: docs/metadata

      - name: Restore centos metadata artifacts
        uses: actions/download-artifact@v2
        with:
          name: metadata-centos
          path: docs/metadata

      - name: Restore debian metadata artifacts
        uses: actions/download-artifact@v2
        with:
          name: metadata-debian
          path: docs/metadata

      - name: Restore fedora metadata artifacts
        uses: actions/download-artifact@v2
        with:
          name: metadata-fedora
          path: docs/metadata

      - name: Restore ubuntu metadata artifacts
        uses: actions/download-artifact@v2
        with:
          name: metadata-ubuntu
          path: docs/metadata

      - name: Push metadata
        run: make auto-commit-metadata
        if: github.ref == 'refs/heads/master'